export const Icons = {
  arrow_down: 'chevron-down',
  arrow_left: 'chevron-left',
  arrow_right: 'chevron-right',
  menu: 'menu',
  record: 'microphone',
  filter: 'tune',
  list: 'format-list-bulleted',
  home: 'home',
  search: 'magnify',
  close: 'close',
  sort_asc: 'sort-alphabetical-ascending',
  sort_desc: 'sort-alphabetical-descending',
  no_internet: 'access-point-remove',
  download: 'cloud-download-outline',
};
